Feature implement service creation
eteg/ecs-deploy-task-definition pull request #1
Opened 2023-10-11 22:52 UTC by tsuyoda

Task: [ALPHA-4702](https://app.clickup.com/t/3097350/ALPHA-4702)

## Testes
Foi criado uma branch de teste no repo do eZSend, contendo uma pipeline utilizando a action desta PR.
https://github.com/eteg/ezsend-monorepo/blob/test-poc-toyoda/.github/workflows/poc.yaml

2023-10-16 17:50 UTC, KayanHendges requested changes

2023-10-16 17:50 UTC, KayanHendges commented on index.js
> +    if (!service) {
Eu entendo que se caso o createServiceIfNotFound fosse false, o serviceInput provavelmente não seria passado e ele não chegaria nessa parte, parando na linha 327. Porém pode acontecer de que os inputs não sejam tão bem compreendidos e quem for chamar a action passe o nome do service que deseja atualizar porém não tenha a intenção de criar o service caso ele não exista (passou o nome errado por exemplo), dessa forma iria criar se não incluir essa variável no if.

Fiz o teste com essas configurações e o service foi criado (pois não existia o 3 ainda)
![image](https://github.com/eteg/ecs-deploy-task-definition/assets/68859964/c62bfb00-5e30-4263-8389-7e321442bd05)


```suggestion
    if (!service && createServiceIfNotFound) {
```

2023-10-16 17:50 UTC, KayanHendges commented on dist/index.js
Aqui eu rodei um yarn package e deu diferença, talvez tenh que rodar de novo

2023-10-16 17:50 UTC, KayanHendges commented on index.js
> +  core.info(`Deployment started. Watch this deployment's progress in the Amazon ECS console: https://${consoleHostname}/ecs/home?region=${aws.config.region}#/clusters/${clusterName}/services/${servic
Seria bom identificar se é um create ou update.

2023-10-16 17:50 UTC, KayanHendges commented on index.js
Eu criei o service-creation-pipeline-test-2 e depois tentei atualizar o desiredCount de 2 para 1 e o schedulingStrategy de REPLICA para DAEMON porém não atualizou. Sabe se é um problema da action ou de como a AWS funciona?

Fiz um novo teste criando um novo service com essas configurações citadas e só ai ele retornou erro 
![image](https://github.com/eteg/ecs-deploy-task-definition/assets/68859964/383f17b4-79af-4404-891b-c683f217f757)

2023-10-16 18:36 UTC, tsuyoda commented on index.js
> +    if (!service) {
Hummm, nesse caso eu acredito que seria melhor eu corrigir a lógica dos inputs, não?

Pois o único intuito do service-config-file, seria a config que o NOVO service deve possuir

Essa action não deve ser responsável por atualizar configurações de service existentes, pois a action original já não é responsável por este tipo de ação... Por isso não faria muito sentido passar essa config ai
Ela até trabalha com atualizações no service, mas somente de atribuir a nova task definition

Permitir o service-config-file sem possuir o create-service-if-not-found ativo, seria uma falha na lógica dos inputs realmente...

2023-10-16 18:59 UTC, KayanHendges commented on index.js
> +    if (!service) {
Acho que faz sentido. Estou de acordo

2023-10-17 17:37 UTC, KayanHendges requested changes

2023-10-17 17:37 UTC, KayanHendges commented on index.js
> +      throw new Error(`Input 'service-config-file' is required only if 'create-service-if-not-found' is true.`);
Acho que como está fica um pouco confuso, invés de "requirido" acho que "permitido" fica mais claro, o que acha?

```suggestion
      throw new Error(`Input 'service-config-file' is allowed only if 'create-service-if-not-found' is true.`); 
```

2023-10-17 17:39 UTC, KayanHendges approved these changes

2023-10-17 20:03 UTC, miacelPereira approved these changes

2023-10-17 20:11 UTC, merged